# Generated by Django 6.0.5 on 2026-05-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavody', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='vysledek',
            name='cas',
            field=models.IntegerField(blank=True, help_text='Čas v sekundách', null=True),
        ),
    ]
